"""Add config

Revision ID: 2ec5f406dc32
Revises: 734c86237fc1
Create Date: 2024-12-04 18:15:39.449271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec5f406dc32'
down_revision: Union[str, None] = '734c86237fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('reactions', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'config')
    op.drop_column('actions', 'config')
    # ### end Alembic commands ###
