"""Fix missing user_id_seq

Revision ID: 00b5f8b31ced
Revises: dd52bb871479
Create Date: 2024-12-07 23:34:05.095053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b5f8b31ced'
down_revision: Union[str, None] = 'dd52bb871479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
