"""Fix users primary key sequence

Revision ID: d69a4b6d9043
Revises: 7b049b642570
Create Date: 2024-12-08 20:20:16.109128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd69a4b6d9043'
down_revision: Union[str, None] = '7b049b642570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column('last_run', sa.DateTime(), nullable=True))
    op.alter_column('triggers', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.execute("""
       SELECT setval('user_id_seq', COALESCE((SELECT MAX(id) FROM users), 1) + 1, false);
       """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('triggers', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('triggers', 'last_run')
    # ### end Alembic commands ###
