"""Add areas auto-increment and other fixes

Revision ID: 8a9168fb0df7
Revises: 2d92830436ae
Create Date: 2024-12-09 00:48:36.018602

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9168fb0df7'
down_revision: Union[str, None] = '2d92830436ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.execute(text("SELECT setval('areas_id_seq', (SELECT MAX(id) FROM areas) + 1)"))
    op.execute(text("SELECT setval('triggers_id_seq', (SELECT MAX(id) FROM triggers) + 1)"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    # ### end Alembic commands ###
