"""Add link

Revision ID: 86cbfd0e2cdb
Revises: 8a9168fb0df7
Create Date: 2024-12-09 01:48:13.005170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cbfd0e2cdb'
down_revision: Union[str, None] = '8a9168fb0df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
