"""make trigger_id nullable

Revision ID: f9b0e0568ff4
Revises: ae574069096e
Create Date: 2025-01-20 01:22:30.776485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b0e0568ff4'
down_revision: Union[str, None] = 'ae574069096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('trigger_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'areas', 'triggers', ['trigger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'trigger_id')
    # ### end Alembic commands ###
