"""add date and hourly trigger

Revision ID: 7a714bf8a184
Revises: f9b0e0568ff4
Create Date: 2025-01-21 00:28:56.937371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a714bf8a184'
down_revision: Union[str, None] = 'f9b0e0568ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('areas_trigger_id_fkey', 'areas', type_='foreignkey')
    op.drop_column('areas', 'trigger_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('trigger_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('areas_trigger_id_fkey', 'areas', 'triggers', ['trigger_id'], ['id'])
    # ### end Alembic commands ###
